const express = require('express')
const router = express.Router()
const controller = require('../controllers/adminController')
const walletController = require('../controllers/walletController')
const { auth, requireAdmin } = require('../middleware/auth')

router.use(auth)
router.get('/me', requireAdmin('stats.view'), controller.me)
router.get('/stats', requireAdmin('stats.view'), controller.stats)
router.get('/reports', requireAdmin('content.manage'), controller.listReports)
router.put('/reports/:id', requireAdmin('content.manage'), controller.updateReport)
router.get('/posts', requireAdmin('content.manage'), controller.listPosts)
router.put('/posts/:id', requireAdmin('content.manage'), controller.updatePost)
router.post('/posts/:id/action', requireAdmin('content.manage'), controller.postAction)
router.post('/posts/batch-action', requireAdmin('content.manage'), controller.batchPostAction)
router.get('/content', requireAdmin('config.manage'), controller.listContent)
router.post('/content', requireAdmin('config.manage'), controller.createContent)
router.put('/content/:id', requireAdmin('config.manage'), controller.updateContent)
router.delete('/content/:id', requireAdmin('config.manage'), controller.deleteContent)
router.get('/features', requireAdmin('config.manage'), controller.listFeatures)
router.put('/features', requireAdmin('config.manage'), controller.saveFeature)
router.get('/items', requireAdmin('item.manage'), controller.listItems)
router.post('/items', requireAdmin('item.manage'), controller.createItem)
router.put('/items/:id', requireAdmin('item.manage'), controller.updateItem)
router.get('/users', requireAdmin('user.manage'), controller.listUsers)
router.put('/users/:id/status', requireAdmin('user.manage'), controller.updateUserStatus)
router.put('/users/:id/role', requireAdmin('role.assign'), controller.updateUserRole)
router.put('/users/:id/cert-label', requireAdmin('user.manage'), controller.updateUserCertLabel)
router.get('/withdrawals', requireAdmin('payment.manage'), walletController.listWithdrawals)
router.post('/withdrawals/:id/review', requireAdmin('payment.manage'), walletController.reviewWithdrawal)
router.get('/rider-verifications', requireAdmin('user.manage'), controller.listRiderVerifications)
router.post('/rider-verifications/:id/review', requireAdmin('user.manage'), controller.reviewRiderVerification)

module.exports = router
