const express = require('express')
const router = express.Router()
const errandController = require('../controllers/errandController')
const paymentController = require('../controllers/paymentController')
const { auth, optionalAuth } = require('../middleware/auth')
const contentSecurity = require('../middleware/contentSecurity')
const idempotency = require('../middleware/idempotency')

router.get('/list', optionalAuth, errandController.list)
router.get('/my-published', auth, errandController.myPublished)
router.get('/my-accepted', auth, errandController.myAccepted)
// 跑腿订单专属聊天（与私信独立）：/chats 为固定路径，必须注册在 /:id 之前
router.get('/chats', auth, errandController.chats)
router.post('/chats/:id/read', auth, errandController.markChatRead)
router.get('/:id/messages', auth, errandController.chatMessages)
// 与 /message/send 保持一致不做文本安全检测（消息 content 可能是图片/视频 URL）
router.post('/:id/messages', auth, errandController.sendChatMessage)
router.post('/cancel-requests/:id/review', auth, errandController.reviewCancelRequest)
router.get('/:id/payment-status', auth, paymentController.queryErrandPaymentStatus)
router.get('/:id', auth, errandController.detail)
router.get('/:id/logs', auth, errandController.logs)
router.post('/', auth, contentSecurity, errandController.create)
router.post('/:id/pay', auth, idempotency, paymentController.createErrandPayment)
router.post('/:id/accept', auth, errandController.accept)
router.post('/:id/release', auth, idempotency, errandController.release)
router.post('/:id/finish', auth, errandController.finish)
router.post('/:id/cancel', auth, idempotency, paymentController.cancelErrand)
router.post('/:id/review', auth, contentSecurity, errandController.review)

module.exports = router
