const express = require('express')
const router = express.Router()
const idempotency = require('../middleware/idempotency')
const userController = require('../controllers/userController')
const uploadController = require('../controllers/uploadController')
const { auth, optionalAuth } = require('../middleware/auth')
const contentSecurity = require('../middleware/contentSecurity')

router.post('/phone-login', userController.phoneLogin)
router.post('/dev-login', userController.devLogin)
router.post('/content-check', auth, contentSecurity, userController.contentCheck)
router.get('/info', auth, userController.getInfo)
router.get('/my-deleted-posts', auth, userController.getMyDeletedPosts)
// Keep compatibility with clients that shipped the underscore variant.
router.get('/my-deleted_posts', auth, userController.getMyDeletedPosts)
router.get('/profile/:id', optionalAuth, userController.getProfile)
router.get('/profile/:id/posts', optionalAuth, userController.getProfilePosts)
router.put('/info', auth, idempotency, contentSecurity, userController.updateInfo)
router.post('/phone', auth, userController.updatePhone)
router.post('/verify', auth, contentSecurity, userController.verify)
router.get('/deletion-request', auth, userController.getDeletionRequest)
router.post('/deletion-request', auth, idempotency, userController.requestDeletion)
router.delete('/deletion-request', auth, userController.cancelDeletion)
router.post('/upload/image', auth, uploadController.uploadMiddleware, uploadController.uploadImage)
router.post('/upload/video', auth, uploadController.uploadVideoMiddleware, uploadController.uploadVideo)
router.get('/interactions/stats', auth, userController.getInteractionStats)
router.get('/interactions/:type', auth, userController.getInteractionList)
router.get('/rider-verification', auth, userController.getRiderVerification)
router.post('/rider-verification', auth, contentSecurity, userController.submitRiderVerification)

module.exports = router
