const profileCovers = {
  community: "/assets/banners/profile-cover.jpg",
  schedule: "/assets/banners/banner-schedule.jpg",
  errand: "/assets/banners/banner-errand.jpg",
};

const banners = [
  {
    id: 1,
    title: "AI 课表助手",
    subtitle: "上传课表截图，自动拆解课程并按类型着色",
    tag: "学习效率",
    image: profileCovers.schedule,
    bg: "linear-gradient(135deg, #4A7AFF 0%, #6B8FFF 100%)",
    link: "/pages/schedule/index",
  },
  {
    id: 2,
    title: "校园即时互助",
    subtitle: "课后取件、代拿跑腿、生活小事快速解决",
    tag: "生活服务",
    image: profileCovers.errand,
    bg: "linear-gradient(135deg, #FF8E53 0%, #FF6B6B 100%)",
    link: "/pages/errand/index",
  },
  {
    id: 3,
    title: "有温度的校园社区",
    subtitle: "发现同校同好，发帖互动并一键发起私信",
    tag: "社区互动",
    image: profileCovers.community,
    bg: "linear-gradient(135deg, #7A5AF8 0%, #9278FF 100%)",
    link: "/pages/index/index",
  },
];

const users = [
  {
    id: 1,
    nickName: "广轻工登山社",
    avatarUrl: "/assets/avatars/avatar-boy-1.png",
    campus: "南海南校区",
    major: "社团组织",
    signature: "每周组织一次轻徒步，欢迎新手一起出发。",
    coverUrl: profileCovers.community,
    verified: true,
    certLabel: "官方社团",
    likeReceived: 921,
  },
  {
    id: 2,
    nickName: "海盐汽水",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    campus: "琶洲校区",
    major: "数字媒体",
    signature: "分享校园穿搭、摄影和一切能让人心情变好的瞬间。",
    coverUrl: profileCovers.schedule,
    verified: false,
    likeReceived: 268,
  },
  {
    id: 3,
    nickName: "旧书中转站",
    avatarUrl: "/assets/avatars/avatar-boy-2.png",
    campus: "南海北校区",
    major: "图书互助",
    signature: "专业课旧书、考证资料长期交换，欢迎留言。",
    coverUrl: profileCovers.errand,
    verified: true,
    certLabel: "认证商家",
    likeReceived: 131,
  },
  {
    id: 4,
    nickName: "礼仪活动发布台",
    avatarUrl: "/assets/avatars/avatar-girl-2.png",
    campus: "新港校区",
    major: "校园活动",
    signature: "校内外活动招募、学时信息、彩排提醒统一发布。",
    coverUrl: profileCovers.community,
    verified: true,
    certLabel: "官方账号",
    likeReceived: 402,
  },
  {
    id: 5,
    nickName: "深夜食堂观察员",
    avatarUrl: "/assets/avatars/avatar-girl-3.png",
    campus: "南海南校区",
    major: "生活分享",
    signature: "记录食堂、夜宵和每一次不想写作业的夜晚。",
    coverUrl: profileCovers.schedule,
    verified: false,
    likeReceived: 96,
  },
];

const homeServices = [
  {
    id: 1,
    name: "二手闲置",
    iconPath: "/assets/icons/svc-idle.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 2,
    name: "订水系统",
    iconPath: "/assets/icons/svc-water.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 3,
    name: "校园卡",
    iconPath: "/assets/icons/svc-card.png",
    badge: "",
    link: "",
  },
  {
    id: 4,
    name: "宅印",
    iconPath: "/assets/icons/svc-print.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 6,
    name: "广轻维修",
      iconPath: "/assets/icons/repair-logo.jpg",
    badge: "推荐",
    route: "/pages/repair/index",
  },
  {
    id: 5,
    name: "校历",
    iconPath: "/assets/icons/svc-calendar.png",
    badge: "新生",
    link: "",
  },
  {
    id: 7,
    name: "自助购电",
    iconPath: "/assets/icons/svc-power.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 8,
    name: "零食店",
    iconPath: "/assets/icons/svc-snack.png",
    badge: "推荐",
    miniAppId: "wx2cd0769ebeb0d213",
  },
  {
    id: 9,
    name: "杂货店",
    iconPath: "/assets/icons/svc-store.png",
    badge: "推荐",
    miniAppId: "wxbe48d181d8d5762e",
  },
  {
    id: 10,
    name: "校园网",
    iconPath: "/assets/icons/svc-network.png",
    badge: "",
    link: "",
  },
];

const allServiceSections = [
  {
    title: "平台自研",
    items: [
      {
        id: 101,
        name: "代拿跑腿",
        iconPath: "/assets/icons/svc-errand.png",
        badge: "推荐",
      },
      {
        id: 102,
        name: "课程表",
        iconPath: "/assets/icons/svc-schedule.png",
        badge: "推荐",
      },
      {
        id: 103,
        name: "社区论坛",
        iconPath: "/assets/icons/svc-community.png",
        badge: "",
      },
    ],
  },
  {
    title: "校园服务",
    items: homeServices,
  },
  {
    title: "学习相关",
    items: [
      {
        id: 201,
        name: "图书馆",
        iconPath: "/assets/icons/svc-library.png",
        badge: "",
      },
      {
        id: 202,
        name: "选课系统",
        iconPath: "/assets/icons/svc-edit.png",
        badge: "",
      },
      {
        id: 203,
        name: "成绩查询",
        iconPath: "/assets/icons/svc-grade.png",
        badge: "",
      },
      {
        id: 204,
        name: "考试安排",
        iconPath: "/assets/icons/svc-exam.png",
        badge: "",
      },
      {
        id: 205,
        name: "教务系统",
        iconPath: "/assets/icons/svc-edu.png",
        badge: "推荐",
        link: "https://jw.gdipu.edu.cn/jsxsd",
      },
    ],
  },
  {
    title: "生活服务",
    items: [
      {
        id: 301,
        name: "食堂菜单",
        iconPath: "/assets/icons/svc-canteen.png",
        badge: "推荐",
        miniAppId: "wx7b3c69b4b6b348d5",
      },
      {
        id: 302,
        name: "校车时刻",
        iconPath: "/assets/icons/svc-bus.png",
        badge: "",
      },
      {
        id: 303,
        name: "失物招领",
        iconPath: "/assets/icons/svc-search.png",
        badge: "",
      },
      {
        id: 304,
        name: "校园地图",
        iconPath: "/assets/icons/svc-map.png",
        badge: "新生",
      },
      {
        id: 305,
        name: "乘车码",
        iconPath: "/assets/icons/svc-card.png",
        badge: "推荐",
        miniAppId: "wxe9f4a4df3ac90522",
      },
    ],
  },
  {
    title: "校园资讯",
    items: [
      {
        id: 401,
        name: "通知公告",
        iconPath: "/assets/icons/svc-notice.png",
        badge: "",
      },
    ],
  },
];

const categories = [
  "最新",
  "最热",
  "日常话题",
  "表白交友",
  "二手闲置",
  "失物寻物",
  "树洞吐槽",
  "组队拼车",
];

const posts = [
  {
    id: 1,
    userId: 1,
    nickName: "广轻工登山社",
    avatarUrl: "/assets/avatars/avatar-boy-1.png",
    category: "打听求助",
    title: "万能的吧友，登山杖选碳纤还是铝合金？",
    content:
      "最近准备去鼎湖山徒步，第一次认真买装备，预算在 150 左右。想问下大家更推荐全碳还是铝合金，主要担心耐用和重量之间怎么平衡。如果有你们正在用的型号，也欢迎直接甩链接或者使用体验。",
    images: [
      "/assets/banners/banner-community.jpg",
      "/assets/banners/banner-schedule.jpg",
    ],
    viewCount: 2651,
    likeCount: 396,
    commentCount: 143,
    favoriteCount: 88,
    shareCount: 16,
    isLiked: false,
    isFavorited: false,
    verified: true,
    certLabel: "官方社团",
    postCount: 18,
    isHot: true,
    createdAt: "2026-06-27T18:30:00",
  },
  {
    id: 2,
    userId: 2,
    nickName: "海盐汽水",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    category: "日常分享",
    title: "阿根廷球衣这个配色真的很适合夏天",
    content:
      "今天在校门口看到这件蓝白条真的很上镜，准备周末拍一组操场写真。顺便问下，有没有人想一起拼个摄影外拍？我可以负责修图和调色。",
    images: ["/assets/banners/banner-community.jpg"],
    viewCount: 1948,
    likeCount: 651,
    commentCount: 143,
    favoriteCount: 126,
    shareCount: 10,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 12,
    isHot: false,
    createdAt: "2026-06-27T12:05:00",
  },
  {
    id: 3,
    userId: 4,
    nickName: "礼仪活动发布台",
    avatarUrl: "/assets/avatars/avatar-girl-2.png",
    category: "校园活动",
    title: "下周校外礼仪活动招募，还差 6 位女生",
    content:
      "正式活动安排在下周四下午 2:30，周三 3:00 需要彩排，车费学校报销，可请公假并加学时。头发不能是浅色，着装需按统一要求准备，感兴趣的同学可以直接私信我了解细节。",
    images: [],
    viewCount: 721,
    likeCount: 319,
    commentCount: 108,
    favoriteCount: 54,
    shareCount: 8,
    isLiked: false,
    isFavorited: false,
    verified: true,
    certLabel: "官方账号",
    postCount: 24,
    isHot: false,
    createdAt: "2026-06-26T16:20:00",
  },
  {
    id: 4,
    userId: 3,
    nickName: "旧书中转站",
    avatarUrl: "/assets/avatars/avatar-boy-2.png",
    category: "旧书交易",
    title: "收世界旅游地理和英语期末复习资料",
    content:
      "优先收有笔记的教材，也可以交换我手里的机械制图参考书。佛山校区线下自提，有意向的同学留言或者私信都可以。",
    images: ["/assets/banners/banner-schedule.jpg"],
    viewCount: 418,
    likeCount: 86,
    commentCount: 27,
    favoriteCount: 35,
    shareCount: 4,
    isLiked: false,
    isFavorited: false,
    verified: true,
    certLabel: "认证商家",
    postCount: 9,
    isHot: false,
    createdAt: "2026-06-25T20:10:00",
  },
  {
    id: 5,
    userId: 5,
    nickName: "深夜食堂观察员",
    avatarUrl: "/assets/avatars/avatar-girl-3.png",
    category: "推荐",
    title: "谁偷了我刚拿到的寿司外卖",
    content:
      "明明取餐柜写着 3 号柜，打开只剩一张小票。想问下有没有同学拿错了，如果你正在图书馆附近看到一份鳗鱼寿司，请及时联系我，真的饿到要哭。",
    images: [],
    viewCount: 1103,
    likeCount: 205,
    commentCount: 52,
    favoriteCount: 14,
    shareCount: 6,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 6,
    isHot: false,
    createdAt: "2026-06-24T21:38:00",
  },
  {
    id: 6,
    userId: 6,
    nickName: "学习委员",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    category: "学习经验",
    title: "四级备考经验分享，一次过 550+",
    content:
      "分享一下我的四级备考经验：\n\n1. 单词是基础，每天背 50 个，用 APP 打卡\n2. 听力每天练 30 分钟，精听真题\n3. 阅读先做细节题，再做主旨题\n4. 写作背模板，但要学会灵活套用\n5. 考前一周每天做一套真题\n\n坚持两个月，稳过！",
    images: [],
    viewCount: 1856,
    likeCount: 423,
    commentCount: 89,
    favoriteCount: 156,
    shareCount: 34,
    isLiked: false,
    isFavorited: false,
    verified: true,
    certLabel: "校园达人",
    postCount: 15,
    isHot: true,
    createdAt: "2026-06-23T14:20:00",
  },
  {
    id: 7,
    userId: 7,
    nickName: "篮球少年",
    avatarUrl: "/assets/avatars/avatar-boy-2.png",
    category: "校园活动",
    title: "周五晚上篮球约战，3v3 半场",
    content:
      "这周五晚上 7 点，南校区篮球场 3 号场，3v3 半场。\n\n目前已有 4 人，还差 2 人。\n\n要求：有一定篮球基础，能跑能跳就行。\n\n自带水，场费 AA。\n\n评论区报名！",
    images: ["/assets/banners/banner-community.jpg"],
    viewCount: 892,
    likeCount: 167,
    commentCount: 45,
    favoriteCount: 23,
    shareCount: 8,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 8,
    isHot: false,
    createdAt: "2026-06-22T19:30:00",
  },
  {
    id: 8,
    userId: 8,
    nickName: "摄影爱好者",
    avatarUrl: "/assets/avatars/avatar-girl-2.png",
    category: "日常分享",
    title: "校园樱花开了，分享一组美图",
    content:
      "今天路过行政楼发现樱花开了！超级美！\n\n最佳观赏地点：\n- 行政楼前大道\n- 图书馆东侧小路\n- 南门入口\n\n推荐早上或傍晚去拍照，光线最好。\n\n花期大概还有一周，想看的同学抓紧啦～",
    images: ["/assets/banners/banner-community.jpg", "/assets/banners/banner-schedule.jpg"],
    viewCount: 2134,
    likeCount: 567,
    commentCount: 78,
    favoriteCount: 234,
    shareCount: 45,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 22,
    isHot: true,
    createdAt: "2026-06-21T16:45:00",
  },
  {
    id: 9,
    userId: 1,
    nickName: "广轻工登山社",
    avatarUrl: "/assets/avatars/avatar-boy-1.png",
    category: "二手",
    title: "出二手山地自行车，9 成新",
    content:
      "去年买的捷安特山地车，27 速，骑行不到 500 公里。\n\n原价 1800，现价 1200 出。\n\n送车锁、打气筒、手机支架。\n\n南校区面交，支持验车。\n\n有意私聊～",
    images: [],
    viewCount: 678,
    likeCount: 89,
    commentCount: 34,
    favoriteCount: 45,
    shareCount: 12,
    isLiked: false,
    isFavorited: false,
    verified: true,
    certLabel: "官方社团",
    postCount: 18,
    isHot: false,
    createdAt: "2026-06-20T11:20:00",
  },
  {
    id: 10,
    userId: 2,
    nickName: "海盐汽水",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    category: "打听求助",
    title: "求推荐南海好吃的火锅店",
    content:
      "周末想和朋友去吃火锅，求推荐南海校区附近好吃的火锅店！\n\n要求：\n- 人均 80 以内\n- 味道好\n- 环境干净\n\n有去过的同学推荐一下吗？",
    images: [],
    viewCount: 534,
    likeCount: 78,
    commentCount: 56,
    favoriteCount: 23,
    shareCount: 5,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 12,
    isHot: false,
    createdAt: "2026-06-19T18:10:00",
  },
];

const errandOrders = [
  {
    id: 1,
    type: "快递",
    campus: "佛山校区",
    title: "帮取菜鸟驿站快递",
    desc: "一个小包裹，不重",
    reward: 5,
    pickupAddr: "菜鸟驿站A区",
    deliveryAddr: "6号宿舍楼",
    status: "pending",
    publisherName: "张同学",
    createdAt: "2026-06-17T11:00:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
  {
    id: 2,
    type: "外卖",
    campus: "广州校区",
    title: "帮取外卖到图书馆",
    desc: "麦当劳，已付款",
    reward: 8,
    pickupAddr: "北门外卖柜",
    deliveryAddr: "图书馆3楼",
    status: "pending",
    publisherName: "李同学",
    createdAt: "2026-06-17T10:45:00",
    itemCount: 2,
    pickupTimeType: "预约",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: true,
  },
  {
    id: 3,
    type: "文件资料",
    campus: "佛山校区",
    title: "帮打印论文并送到办公室",
    desc: "黑白打印约20页",
    reward: 10,
    pickupAddr: "打印店",
    deliveryAddr: "行政楼201",
    status: "pending",
    publisherName: "王同学",
    createdAt: "2026-06-17T09:30:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
  {
    id: 4,
    type: "快递",
    campus: "广州校区",
    title: "帮取京东快递",
    desc: "中等大小箱子，需要搬上3楼",
    reward: 8,
    pickupAddr: "京东快递点",
    deliveryAddr: "12栋305",
    status: "pending",
    publisherName: "陈同学",
    createdAt: "2026-06-16T15:20:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "限男生",
    isLargeItem: true,
    isUrgent: false,
  },
  {
    id: 5,
    type: "帮买物品",
    campus: "佛山校区",
    title: "帮忙买感冒药",
    desc: "校医院旁边药店买一盒感冒药",
    reward: 6,
    pickupAddr: "校医院旁药店",
    deliveryAddr: "15栋310",
    status: "pending",
    publisherName: "刘同学",
    createdAt: "2026-06-16T14:10:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
  {
    id: 6,
    type: "外卖",
    campus: "佛山校区",
    title: "帮取奶茶",
    desc: "喜茶一杯，已下单",
    reward: 4,
    pickupAddr: "南门外卖柜",
    deliveryAddr: "图书馆2楼",
    status: "pending",
    publisherName: "赵同学",
    createdAt: "2026-06-16T13:30:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
  {
    id: 7,
    type: "其他",
    campus: "广州校区",
    title: "帮忙占座",
    desc: "图书馆4楼靠窗位置，占2小时",
    reward: 5,
    pickupAddr: "图书馆4楼",
    deliveryAddr: "图书馆4楼",
    status: "pending",
    publisherName: "孙同学",
    createdAt: "2026-06-16T12:00:00",
    itemCount: 1,
    pickupTimeType: "预约",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
  {
    id: 8,
    type: "快递",
    campus: "佛山校区",
    title: "帮取顺丰快递",
    desc: "文件袋，比较轻",
    reward: 4,
    pickupAddr: "顺丰快递点",
    deliveryAddr: "8栋520",
    status: "pending",
    publisherName: "周同学",
    createdAt: "2026-06-16T10:45:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
  },
];

// 我发布的订单
const myPublishedOrders = [
  {
    id: 101,
    type: "快递",
    campus: "广州校区",
    title: "帮取顺丰快递",
    desc: "中等箱子，需搬上3楼",
    reward: 6,
    pickupAddr: "顺丰营业点",
    deliveryAddr: "8栋302",
    status: "accepted",
    publisherName: "我",
    accepterName: "陈同学",
    createdAt: "2026-06-16T15:00:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "限男生",
    isLargeItem: true,
    isUrgent: false,
    role: "publisher",
  },
  {
    id: 102,
    type: "外卖",
    campus: "广州校区",
    title: "代取奶茶",
    desc: "一点喜茶，已下单",
    reward: 4,
    pickupAddr: "喜茶(广州店)",
    deliveryAddr: "图书馆2楼",
    status: "finished",
    publisherName: "我",
    accepterName: "林同学",
    createdAt: "2026-06-15T14:20:00",
    itemCount: 2,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
    role: "publisher",
  },
  {
    id: 103,
    type: "快递",
    campus: "佛山校区",
    title: "取京东快递",
    desc: "小件",
    reward: 3,
    pickupAddr: "京东自提柜",
    deliveryAddr: "5栋101",
    status: "pending",
    publisherName: "我",
    accepterName: "",
    createdAt: "2026-06-17T08:00:00",
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
    role: "publisher",
  },
];

// 我接的订单
const myAcceptedOrders = [
  {
    id: 201,
    type: "快递",
    campus: "广州校区",
    title: "帮取菜鸟驿站大件",
    desc: "一个行李箱大小",
    reward: 12,
    pickupAddr: "菜鸟驿站B区",
    deliveryAddr: "12栋505",
    status: "accepted",
    publisherName: "赵同学",
    accepterName: "我",
    createdAt: "2026-06-17T10:00:00",
    acceptedAt: new Date().toISOString(),
    itemCount: 1,
    pickupTimeType: "尽快",
    genderRequirement: "限男生",
    isLargeItem: true,
    isUrgent: false,
    role: "accepter",
  },
  {
    id: 202,
    type: "其他",
    campus: "佛山校区",
    title: "代买教材",
    desc: "书店选购两本教材",
    reward: 8,
    pickupAddr: "校园书店",
    deliveryAddr: "教学楼A",
    status: "finished",
    publisherName: "孙同学",
    accepterName: "我",
    createdAt: "2026-06-14T09:30:00",
    itemCount: 2,
    pickupTimeType: "预约",
    genderRequirement: "不限性别",
    isLargeItem: false,
    isUrgent: false,
    role: "accepter",
  },
];

const courseColors = [
  "#4A7AFF",
  "#52C41A",
  "#FAAD14",
  "#FF4D4F",
  "#722ED1",
  "#13C2C2",
  "#EB2F96",
  "#FA8C16",
  "#2F54EB",
  "#A0D911",
  "#F759AB",
  "#36CFC9",
];

// ===== 私信 Mock 数据 =====
const mockConversations = [
  {
    peerId: 2,
    peerNick: "海盐汽水",
    peerAvatar: "/assets/avatars/avatar-girl-1.png",
    unreadCount: 2,
    lastMessage: "好的，那我们周末图书馆见~",
    lastTime: "2026-08-22T14:30:00"
  },
  {
    peerId: 1,
    peerNick: "广轻工登山社",
    peerAvatar: "/assets/avatars/avatar-boy-1.png",
    unreadCount: 0,
    lastMessage: "这周六早上8点南门集合，记得带水和防晒霜",
    lastTime: "2026-08-21T20:15:00"
  },
  {
    peerId: 3,
    peerNick: "旧书中转站",
    peerAvatar: "/assets/avatars/avatar-boy-2.png",
    unreadCount: 1,
    lastMessage: "那本机械制图还在，你什么时候方便来拿？",
    lastTime: "2026-08-20T16:45:00"
  }
];

const mockMessages = {
  2: [
    { id: 1001, senderId: 2, receiverId: 100, content: "你好！看到你在论坛发的摄影外拍招募，我很感兴趣~", msgType: "text", status: "read", createdAt: "2026-08-22T10:00:00" },
    { id: 1002, senderId: 100, receiverId: 2, content: "太好了！我计划这周末去操场拍一组，你有空吗？", msgType: "text", status: "read", createdAt: "2026-08-22T10:05:00" },
    { id: 1003, senderId: 2, receiverId: 100, content: "有的！周六下午可以吗？我上午有课", msgType: "text", status: "read", createdAt: "2026-08-22T10:08:00" },
    { id: 1004, senderId: 100, receiverId: 2, content: "没问题，那周六下午3点图书馆门口见？", msgType: "text", status: "read", createdAt: "2026-08-22T10:10:00" },
    { id: 1005, senderId: 2, receiverId: 100, content: "好的，那我们周末图书馆见~", msgType: "text", status: "delivered", createdAt: "2026-08-22T14:30:00" },
    { id: 1006, senderId: 2, receiverId: 100, content: "对了，需要我带什么器材吗？", msgType: "text", status: "delivered", createdAt: "2026-08-22T14:31:00" }
  ],
  1: [
    { id: 2001, senderId: 1, receiverId: 100, content: "同学你好，欢迎加入登山社！", msgType: "text", status: "read", createdAt: "2026-08-20T09:00:00" },
    { id: 2002, senderId: 100, receiverId: 1, content: "谢谢！请问这周末的活动具体怎么安排？", msgType: "text", status: "read", createdAt: "2026-08-20T09:10:00" },
    { id: 2003, senderId: 1, receiverId: 100, content: "这周六早上8点南门集合，记得带水和防晒霜", msgType: "text", status: "read", createdAt: "2026-08-21T20:15:00" }
  ],
  3: [
    { id: 3001, senderId: 100, receiverId: 3, content: "你好，请问你那本机械制图参考书还在吗？", msgType: "text", status: "read", createdAt: "2026-08-19T14:00:00" },
    { id: 3002, senderId: 3, receiverId: 100, content: "在的！你想用哪本书交换？", msgType: "text", status: "read", createdAt: "2026-08-19T15:30:00" },
    { id: 3003, senderId: 100, receiverId: 3, content: "我有世界旅游地理和英语期末复习资料", msgType: "text", status: "read", createdAt: "2026-08-19T15:35:00" },
    { id: 3004, senderId: 3, receiverId: 100, content: "那本机械制图还在，你什么时候方便来拿？", msgType: "text", status: "delivered", createdAt: "2026-08-20T16:45:00" }
  ]
};

// ===== 钱包 Mock 数据 =====
// 结构与后端 GET /wallet/summary 返回保持一致
const walletSummary = {
  available: 36.5,
  earned: 128,
  withdrawing: 12,
  records: [
    { id: 5001, type: "errand_earning", amount: 8, title: "跑腿订单收入 #202", status: "success", createdAt: "2026-08-20T18:30:00" },
    { id: 5002, type: "withdrawal", amount: -20, title: "提现至微信零钱", status: "success", createdAt: "2026-08-18T10:00:00" },
    { id: 5003, type: "errand_earning", amount: 6, title: "跑腿订单收入 #201", status: "success", createdAt: "2026-08-16T15:20:00" },
    { id: 5004, type: "withdrawal", amount: -12, title: "提现至微信零钱（审核中）", status: "pending", createdAt: "2026-08-22T09:10:00" },
    { id: 5005, type: "errand_earning", amount: 4, title: "跑腿订单收入 #102", status: "success", createdAt: "2026-06-15T14:30:00" }
  ]
};

module.exports = {
  profileCovers,
  users,
  banners,
  homeServices,
  allServiceSections,
  categories,
  posts,
  errandOrders,
  myPublishedOrders,
  myAcceptedOrders,
  courseColors,
  mockConversations,
  mockMessages,
  walletSummary,
};
