const profileCovers = {
  community: "/assets/banners/banner-community.png",
  schedule: "/assets/banners/banner-schedule.png",
  errand: "/assets/banners/banner-errand.png",
};

const banners = [
  {
    id: 1,
    title: "AI 课表助手",
    subtitle: "上传课表截图，自动拆解课程并按类型着色",
    tag: "学习效率",
    image: profileCovers.schedule,
    bg: "linear-gradient(135deg, #4A7AFF 0%, #6B8FFF 100%)",
    link: "/pages/schedule/index",
  },
  {
    id: 2,
    title: "校园即时互助",
    subtitle: "课后取件、代拿跑腿、生活小事快速解决",
    tag: "生活服务",
    image: profileCovers.errand,
    bg: "linear-gradient(135deg, #FF8E53 0%, #FF6B6B 100%)",
    link: "/pages/errand/index",
  },
  {
    id: 3,
    title: "有温度的校园社区",
    subtitle: "发现同校同好，发帖互动并一键发起私信",
    tag: "社区互动",
    image: profileCovers.community,
    bg: "linear-gradient(135deg, #7A5AF8 0%, #9278FF 100%)",
    link: "/pages/index/index",
  },
];

const users = [
  {
    id: 1,
    nickName: "广轻工登山社",
    avatarUrl: "/assets/avatars/avatar-boy-1.png",
    campus: "佛山校区",
    major: "社团组织",
    signature: "每周组织一次轻徒步，欢迎新手一起出发。",
    coverUrl: profileCovers.community,
    verified: true,
    likeReceived: 921,
  },
  {
    id: 2,
    nickName: "海盐汽水",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    campus: "广州校区",
    major: "数字媒体",
    signature: "分享校园穿搭、摄影和一切能让人心情变好的瞬间。",
    coverUrl: profileCovers.schedule,
    verified: false,
    likeReceived: 268,
  },
  {
    id: 3,
    nickName: "旧书中转站",
    avatarUrl: "/assets/avatars/avatar-boy-2.png",
    campus: "佛山校区",
    major: "图书互助",
    signature: "专业课旧书、考证资料长期交换，欢迎留言。",
    coverUrl: profileCovers.errand,
    verified: true,
    likeReceived: 131,
  },
  {
    id: 4,
    nickName: "礼仪活动发布台",
    avatarUrl: "/assets/avatars/avatar-girl-2.png",
    campus: "广州校区",
    major: "校园活动",
    signature: "校内外活动招募、学时信息、彩排提醒统一发布。",
    coverUrl: profileCovers.community,
    verified: true,
    likeReceived: 402,
  },
  {
    id: 5,
    nickName: "深夜食堂观察员",
    avatarUrl: "/assets/avatars/avatar-girl-3.png",
    campus: "佛山校区",
    major: "生活分享",
    signature: "记录食堂、夜宵和每一次不想写作业的夜晚。",
    coverUrl: profileCovers.schedule,
    verified: false,
    likeReceived: 96,
  },
];

const homeServices = [
  {
    id: 1,
    name: "二手闲置",
    iconPath: "/assets/icons/svc-idle.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 2,
    name: "订水系统",
    iconPath: "/assets/icons/svc-water.png",
    badge: "推荐",
    link: "http://wx.dingbaoxiaoyuan.com/home",
  },
  {
    id: 3,
    name: "校园卡",
    iconPath: "/assets/icons/svc-card.png",
    badge: "",
    link: "",
  },
  {
    id: 4,
    name: "宅印",
    iconPath: "/assets/icons/svc-print.png",
    badge: "推荐",
    link: "",
  },
  {
    id: 5,
    name: "校历",
    iconPath: "/assets/icons/svc-calendar.png",
    badge: "新生",
    link: "",
  },
  {
    id: 7,
    name: "自助购电",
    iconPath: "/assets/icons/svc-power.png",
    badge: "推荐",
    link: "http://bd.bdfairy.cn",
  },
  {
    id: 8,
    name: "零食店",
    iconPath: "/assets/icons/svc-snack.png",
    badge: "推荐",
    miniAppId: "wx2cd0769ebeb0d213",
  },
  {
    id: 9,
    name: "杂货店",
    iconPath: "/assets/icons/svc-store.png",
    badge: "推荐",
    miniAppId: "wxbe48d181d8d5762e",
  },
  {
    id: 10,
    name: "校园网",
    iconPath: "/assets/icons/svc-network.png",
    badge: "",
    link: "",
  },
];

const allServiceSections = [
  {
    title: "平台自研",
    items: [
      {
        id: 101,
        name: "代拿跑腿",
        iconPath: "/assets/icons/svc-errand.png",
        badge: "推荐",
      },
      {
        id: 102,
        name: "课程表",
        iconPath: "/assets/icons/svc-schedule.png",
        badge: "推荐",
      },
      {
        id: 103,
        name: "社区论坛",
        iconPath: "/assets/icons/svc-community.png",
        badge: "",
      },
    ],
  },
  {
    title: "校园服务",
    items: homeServices,
  },
  {
    title: "学习相关",
    items: [
      {
        id: 201,
        name: "图书馆",
        iconPath: "/assets/icons/svc-library.png",
        badge: "",
      },
      {
        id: 202,
        name: "选课系统",
        iconPath: "/assets/icons/svc-edit.png",
        badge: "",
      },
      {
        id: 203,
        name: "成绩查询",
        iconPath: "/assets/icons/svc-grade.png",
        badge: "",
      },
      {
        id: 204,
        name: "考试安排",
        iconPath: "/assets/icons/svc-exam.png",
        badge: "",
      },
      {
        id: 205,
        name: "教务系统",
        iconPath: "/assets/icons/svc-edu.png",
        badge: "推荐",
        link: "http://jw.gdip.edu.cn/jsxsd",
      },
    ],
  },
  {
    title: "生活服务",
    items: [
      {
        id: 301,
        name: "食堂菜单",
        iconPath: "/assets/icons/svc-canteen.png",
        badge: "推荐",
        miniAppId: "wx7b3c69b4b6b348d5",
      },
      {
        id: 302,
        name: "校车时刻",
        iconPath: "/assets/icons/svc-bus.png",
        badge: "",
      },
      {
        id: 303,
        name: "失物招领",
        iconPath: "/assets/icons/svc-search.png",
        badge: "",
      },
      {
        id: 304,
        name: "校园地图",
        iconPath: "/assets/icons/svc-map.png",
        badge: "新生",
      },
      {
        id: 305,
        name: "乘车码",
        iconPath: "/assets/icons/svc-card.png",
        badge: "推荐",
        miniAppId: "wxe9f4a4df3ac90522",
      },
    ],
  },
  {
    title: "校园资讯",
    items: [
      {
        id: 401,
        name: "通知公告",
        iconPath: "/assets/icons/svc-notice.png",
        badge: "",
      },
    ],
  },
];

const categories = [
  "全部帖子",
  "推荐",
  "日常分享",
  "旧书交易",
  "校园活动",
  "打听求助",
  "二手",
];

const posts = [
  {
    id: 1,
    userId: 1,
    nickName: "广轻工登山社",
    avatarUrl: "/assets/avatars/avatar-boy-1.png",
    category: "打听求助",
    title: "万能的吧友，登山杖选碳纤还是铝合金？",
    content:
      "最近准备去鼎湖山徒步，第一次认真买装备，预算在 150 左右。想问下大家更推荐全碳还是铝合金，主要担心耐用和重量之间怎么平衡。如果有你们正在用的型号，也欢迎直接甩链接或者使用体验。",
    images: [
      "/assets/banners/banner-community.png",
      "/assets/banners/banner-schedule.png",
    ],
    viewCount: 2651,
    likeCount: 396,
    commentCount: 143,
    favoriteCount: 88,
    shareCount: 16,
    isLiked: false,
    isFavorited: false,
    verified: true,
    postCount: 18,
    isHot: true,
    createdAt: "2026-06-27T18:30:00",
  },
  {
    id: 2,
    userId: 2,
    nickName: "海盐汽水",
    avatarUrl: "/assets/avatars/avatar-girl-1.png",
    category: "日常分享",
    title: "阿根廷球衣这个配色真的很适合夏天",
    content:
      "今天在校门口看到这件蓝白条真的很上镜，准备周末拍一组操场写真。顺便问下，有没有人想一起拼个摄影外拍？我可以负责修图和调色。",
    images: ["/assets/banners/banner-community.png"],
    viewCount: 1948,
    likeCount: 651,
    commentCount: 143,
    favoriteCount: 126,
    shareCount: 10,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 12,
    isHot: false,
    createdAt: "2026-06-27T12:05:00",
  },
  {
    id: 3,
    userId: 4,
    nickName: "礼仪活动发布台",
    avatarUrl: "/assets/avatars/avatar-girl-2.png",
    category: "校园活动",
    title: "下周校外礼仪活动招募，还差 6 位女生",
    content:
      "正式活动安排在下周四下午 2:30，周三 3:00 需要彩排，车费学校报销，可请公假并加学时。头发不能是浅色，着装需按统一要求准备，感兴趣的同学可以直接私信我了解细节。",
    images: [],
    viewCount: 721,
    likeCount: 319,
    commentCount: 108,
    favoriteCount: 54,
    shareCount: 8,
    isLiked: false,
    isFavorited: false,
    verified: true,
    postCount: 24,
    isHot: false,
    createdAt: "2026-06-26T16:20:00",
  },
  {
    id: 4,
    userId: 3,
    nickName: "旧书中转站",
    avatarUrl: "/assets/avatars/avatar-boy-2.png",
    category: "旧书交易",
    title: "收世界旅游地理和英语期末复习资料",
    content:
      "优先收有笔记的教材，也可以交换我手里的机械制图参考书。佛山校区线下自提，有意向的同学留言或者私信都可以。",
    images: ["/assets/banners/banner-schedule.png"],
    viewCount: 418,
    likeCount: 86,
    commentCount: 27,
    favoriteCount: 35,
    shareCount: 4,
    isLiked: false,
    isFavorited: false,
    verified: true,
    postCount: 9,
    isHot: false,
    createdAt: "2026-06-25T20:10:00",
  },
  {
    id: 5,
    userId: 5,
    nickName: "深夜食堂观察员",
    avatarUrl: "/assets/avatars/avatar-girl-3.png",
    category: "推荐",
    title: "谁偷了我刚拿到的寿司外卖",
    content:
      "明明取餐柜写着 3 号柜，打开只剩一张小票。想问下有没有同学拿错了，如果你正在图书馆附近看到一份鳗鱼寿司，请及时联系我，真的饿到要哭。",
    images: [],
    viewCount: 1103,
    likeCount: 205,
    commentCount: 52,
    favoriteCount: 14,
    shareCount: 6,
    isLiked: false,
    isFavorited: false,
    verified: false,
    postCount: 6,
    isHot: false,
    createdAt: "2026-06-24T21:38:00",
  },
];

const errandOrders = [
  {
    id: 1,
    type: "快递",
    campus: "佛山校区",
    title: "帮取菜鸟驿站快递",
    desc: "一个小包裹，不重",
    reward: 5,
    pickupAddr: "菜鸟驿站A区",
    deliveryAddr: "6号宿舍楼",
    status: "pending",
    publisherName: "张同学",
    createdAt: "2026-06-17T11:00:00",
    itemCount: 1,
    timeLimit: "不限时间",
    genderReq: "不限性别",
    noUpstairs: false,
  },
  {
    id: 2,
    type: "外卖",
    campus: "广州校区",
    title: "帮取外卖到图书馆",
    desc: "麦当劳，已付款",
    reward: 8,
    pickupAddr: "北门外卖柜",
    deliveryAddr: "图书馆3楼",
    status: "pending",
    publisherName: "李同学",
    createdAt: "2026-06-17T10:45:00",
    itemCount: 2,
    timeLimit: "1小时内",
    genderReq: "不限性别",
    noUpstairs: false,
  },
  {
    id: 3,
    type: "代办",
    campus: "佛山校区",
    title: "帮打印论文并送到办公室",
    desc: "黑白打印约20页",
    reward: 10,
    pickupAddr: "打印店",
    deliveryAddr: "行政楼201",
    status: "pending",
    publisherName: "王同学",
    createdAt: "2026-06-17T09:30:00",
    itemCount: 1,
    timeLimit: "今天内",
    genderReq: "不限性别",
    noUpstairs: true,
  },
];

// 我发布的订单
const myPublishedOrders = [
  {
    id: 101,
    type: "快递",
    campus: "广州校区",
    title: "帮取顺丰快递",
    desc: "中等箱子，需搬上3楼",
    reward: 6,
    pickupAddr: "顺丰营业点",
    deliveryAddr: "8栋302",
    status: "accepted",
    publisherName: "我",
    accepterName: "陈同学",
    createdAt: "2026-06-16T15:00:00",
    itemCount: 1,
    timeLimit: "今天内",
    genderReq: "仅限男生",
    noUpstairs: false,
    role: "publisher",
  },
  {
    id: 102,
    type: "外卖",
    campus: "广州校区",
    title: "代取奶茶",
    desc: "一点喜茶，已下单",
    reward: 4,
    pickupAddr: "喜茶(广州店)",
    deliveryAddr: "图书馆2楼",
    status: "done",
    publisherName: "我",
    accepterName: "林同学",
    createdAt: "2026-06-15T14:20:00",
    itemCount: 2,
    timeLimit: "1小时内",
    genderReq: "不限性别",
    noUpstairs: false,
    role: "publisher",
  },
  {
    id: 103,
    type: "快递",
    campus: "佛山校区",
    title: "取京东快递",
    desc: "小件",
    reward: 3,
    pickupAddr: "京东自提柜",
    deliveryAddr: "5栋101",
    status: "pending",
    publisherName: "我",
    accepterName: "",
    createdAt: "2026-06-17T08:00:00",
    itemCount: 1,
    timeLimit: "不限时间",
    genderReq: "不限性别",
    noUpstairs: true,
    role: "publisher",
  },
];

// 我接的订单
const myAcceptedOrders = [
  {
    id: 201,
    type: "快递",
    campus: "广州校区",
    title: "帮取菜鸟驿站大件",
    desc: "一个行李箱大小",
    reward: 12,
    pickupAddr: "菜鸟驿站B区",
    deliveryAddr: "12栋505",
    status: "accepted",
    publisherName: "赵同学",
    accepterName: "我",
    createdAt: "2026-06-17T10:00:00",
    itemCount: 1,
    timeLimit: "2小时内",
    genderReq: "仅限男生",
    noUpstairs: false,
    role: "accepter",
  },
  {
    id: 202,
    type: "代办",
    campus: "佛山校区",
    title: "代买教材",
    desc: "书店选购两本教材",
    reward: 8,
    pickupAddr: "校园书店",
    deliveryAddr: "教学楼A",
    status: "done",
    publisherName: "孙同学",
    accepterName: "我",
    createdAt: "2026-06-14T09:30:00",
    itemCount: 2,
    timeLimit: "今天内",
    genderReq: "不限性别",
    noUpstairs: false,
    role: "accepter",
  },
];

const courseColors = [
  "#4A7AFF",
  "#52C41A",
  "#FAAD14",
  "#FF4D4F",
  "#722ED1",
  "#13C2C2",
  "#EB2F96",
  "#FA8C16",
  "#2F54EB",
  "#A0D911",
  "#F759AB",
  "#36CFC9",
];

module.exports = {
  profileCovers,
  users,
  banners,
  homeServices,
  allServiceSections,
  categories,
  posts,
  errandOrders,
  myPublishedOrders,
  myAcceptedOrders,
  courseColors,
};
